In [1]:
#Import the libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_e705c530702f4f748fe2bcd326eddf48 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='5vWts9gAyXRwwLPS2Wl3ea-RxZNlPxP0rgyGE9vyNHZi',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_e705c530702f4f748fe2bcd326eddf48.get_object(Bucket='vamsi-donotdelete-pr-4jimyeeksstipn',Key='airquality.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5

In [3]:
dataset

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      NaN      NaN  14.3    56      5    5
5     28.0      NaN  14.9    66      5    6
6     23.0    299.0   8.6    65      5    7
7     19.0     99.0  13.8    59      5    8
8      8.0     19.0  20.1    61      5    9
9      NaN    194.0   8.6    69      5   10
10     7.0      NaN   6.9    74      5   11
11    16.0    256.0   9.7    69      5   12
12    11.0    290.0   9.2    66      5   13
13    14.0    274.0  10.9    68      5   14
14    18.0     65.0  13.2    58      5   15
15    14.0    334.0  11.5    64      5   16
16    34.0    307.0  12.0    66      5   17
17     6.0     78.0  18.4    57      5   18
18    30.0    322.0  11.5    68      5   19
19    11.0     44.0   9.7    62      5   20
20     1.0      8.0   9.7    59      5   21
21    11.0    320.0  16.6    73      5   22
22     4.0     25.0   9.7    61      5   23
23    32.0     92.0  12.0    61      5   24
24     NaN     66.0  16.6    57      5   25
25     NaN    266.0  14.9    58      5   26
26     NaN      NaN   8.0    57      5   27
27    23.0     13.0  12.0    67      5   28
28    45.0    252.0  14.9    81      5   29
29   115.0    223.0   5.7    79      5   30
..     ...      ...   ...   ...    ...  ...
123   96.0    167.0   6.9    91      9    1
124   78.0    197.0   5.1    92      9    2
125   73.0    183.0   2.8    93      9    3
126   91.0    189.0   4.6    93      9    4
127   47.0     95.0   7.4    87      9    5
128   32.0     92.0  15.5    84      9    6
129   20.0    252.0  10.9    80      9    7
130   23.0    220.0  10.3    78      9    8
131   21.0    230.0  10.9    75      9    9
132   24.0    259.0   9.7    73      9   10
133   44.0    236.0  14.9    81      9   11
134   21.0    259.0  15.5    76      9   12
135   28.0    238.0   6.3    77      9   13
136    9.0     24.0  10.9    71      9   14
137   13.0    112.0  11.5    71      9   15
138   46.0    237.0   6.9    78      9   16
139   18.0    224.0  13.8    67      9   17
140   13.0     27.0  10.3    76      9   18
141   24.0    238.0  10.3    68      9   19
142   16.0    201.0   8.0    82      9   20
143   13.0    238.0  12.6    64      9   21
144   23.0     14.0   9.2    71      9   22
145   36.0    139.0  10.3    81      9   23
146    7.0     49.0  10.3    69      9   24
147   14.0     20.0  16.6    63      9   25
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9    3

[153 rows x 6 columns]

In [4]:
dataset.isnull().any()

Ozone       True
Solar.R     True
Wind       False
Temp       False
Month      False
Day        False
dtype: bool

In [5]:
dataset.fillna(dataset.median(),inplace=True)

In [6]:
dataset.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4   31.5    205.0  14.3    56      5    5

In [7]:
dataset.corr()

            Ozone   Solar.R      Wind      Temp     Month       Day
Ozone    1.000000  0.295472 -0.531902  0.600833  0.187597 -0.006222
Solar.R  0.295472  1.000000 -0.057899  0.257154 -0.077812 -0.161489
Wind    -0.531902 -0.057899  1.000000 -0.457988 -0.178293  0.018440
Temp     0.600833  0.257154 -0.457988  1.000000  0.420947 -0.109867
Month    0.187597 -0.077812 -0.178293  0.420947  1.000000 -0.036411
Day     -0.006222 -0.161489  0.018440 -0.109867 -0.036411  1.000000

In [8]:
x = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, 0].values

In [9]:
x

array([[ 190. ,    7.4,   67. ],
       [ 118. ,    8. ,   72. ],
       [ 149. ,   12.6,   74. ],
       [ 313. ,   11.5,   62. ],
       [ 205. ,   14.3,   56. ],
       [ 205. ,   14.9,   66. ],
       [ 299. ,    8.6,   65. ],
       [  99. ,   13.8,   59. ],
       [  19. ,   20.1,   61. ],
       [ 194. ,    8.6,   69. ],
       [ 205. ,    6.9,   74. ],
       [ 256. ,    9.7,   69. ],
       [ 290. ,    9.2,   66. ],
       [ 274. ,   10.9,   68. ],
       [  65. ,   13.2,   58. ],
       [ 334. ,   11.5,   64. ],
       [ 307. ,   12. ,   66. ],
       [  78. ,   18.4,   57. ],
       [ 322. ,   11.5,   68. ],
       [  44. ,    9.7,   62. ],
       [   8. ,    9.7,   59. ],
       [ 320. ,   16.6,   73. ],
       [  25. ,    9.7,   61. ],
       [  92. ,   12. ,   61. ],
       [  66. ,   16.6,   57. ],
       [ 266. ,   14.9,   58. ],
       [ 205. ,    8. ,   57. ],
       [  13. ,   12. ,   67. ],
       [ 252. ,   14.9,   81. ],
       [ 223. ,    5.7,   79. ],
       [ 279. ,    7.4,   76. ],
       [ 286. ,    8.6,   78. ],
       [ 287. ,    9.7,   74. ],
       [ 242. ,   16.1,   67. ],
       [ 186. ,    9.2,   84. ],
       [ 220. ,    8.6,   85. ],
       [ 264. ,   14.3,   79. ],
       [ 127. ,    9.7,   82. ],
       [ 273. ,    6.9,   87. ],
       [ 291. ,   13.8,   90. ],
       [ 323. ,   11.5,   87. ],
       [ 259. ,   10.9,   93. ],
       [ 250. ,    9.2,   92. ],
       [ 148. ,    8. ,   82. ],
       [ 332. ,   13.8,   80. ],
       [ 322. ,   11.5,   79. ],
       [ 191. ,   14.9,   77. ],
       [ 284. ,   20.7,   72. ],
       [  37. ,    9.2,   65. ],
       [ 120. ,   11.5,   73. ],
       [ 137. ,   10.3,   76. ],
       [ 150. ,    6.3,   77. ],
       [  59. ,    1.7,   76. ],
       [  91. ,    4.6,   76. ],
       [ 250. ,    6.3,   76. ],
       [ 135. ,    8. ,   75. ],
       [ 127. ,    8. ,   78. ],
       [  47. ,   10.3,   73. ],
       [  98. ,   11.5,   80. ],
       [  31. ,   14.9,   77. ],
       [ 138. ,    8. ,   83. ],
       [ 269. ,    4.1,   84. ],
       [ 248. ,    9.2,   85. ],
       [ 236. ,    9.2,   81. ],
       [ 101. ,   10.9,   84. ],
       [ 175. ,    4.6,   83. ],
       [ 314. ,   10.9,   83. ],
       [ 276. ,    5.1,   88. ],
       [ 267. ,    6.3,   92. ],
       [ 272. ,    5.7,   92. ],
       [ 175. ,    7.4,   89. ],
       [ 139. ,    8.6,   82. ],
       [ 264. ,   14.3,   73. ],
       [ 175. ,   14.9,   81. ],
       [ 291. ,   14.9,   91. ],
       [  48. ,   14.3,   80. ],
       [ 260. ,    6.9,   81. ],
       [ 274. ,   10.3,   82. ],
       [ 285. ,    6.3,   84. ],
       [ 187. ,    5.1,   87. ],
       [ 220. ,   11.5,   85. ],
       [   7. ,    6.9,   74. ],
       [ 258. ,    9.7,   81. ],
       [ 295. ,   11.5,   82. ],
       [ 294. ,    8.6,   86. ],
       [ 223. ,    8. ,   85. ],
       [  81. ,    8.6,   82. ],
       [  82. ,   12. ,   86. ],
       [ 213. ,    7.4,   88. ],
       [ 275. ,    7.4,   86. ],
       [ 253. ,    7.4,   83. ],
       [ 254. ,    9.2,   81. ],
       [  83. ,    6.9,   81. ],
       [  24. ,   13.8,   81. ],
       [  77. ,    7.4,   82. ],
       [ 205. ,    6.9,   86. ],
       [ 205. ,    7.4,   85. ],
       [ 205. ,    4.6,   87. ],
       [ 255. ,    4. ,   89. ],
       [ 229. ,   10.3,   90. ],
       [ 207. ,    8. ,   90. ],
       [ 222. ,    8.6,   92. ],
       [ 137. ,   11.5,   86. ],
       [ 192. ,   11.5,   86. ],
       [ 273. ,   11.5,   82. ],
       [ 157. ,    9.7,   80. ],
       [  64. ,   11.5,   79. ],
       [  71. ,   10.3,   77. ],
       [  51. ,    6.3,   79. ],
       [ 115. ,    7.4,   76. ],
       [ 244. ,   10.9,   78. ],
       [ 190. ,   10.3,   78. ],
       [ 259. ,   15.5,   77. ],
       [  36. ,   14.3,   72. ],
       [ 255. ,   12.6,   75. ],
       [ 212. ,    9.7,   79. ],
       [ 238. ,    3.4,   81. ],
       [ 215. ,    8. ,   86. ],
       [ 153. ,    5.7,   88. ],
       [ 203. ,    9.7,   97. ],
       [ 225. ,    2.3,   94. ],
       [ 237. ,    6.3,   96. ],
       [ 188. ,    6.3,   94. ],
       [ 167. ,    6.9,   91. ],
       [ 197. ,    5.1,   92. ],
       [ 183. ,    2.8,   93. ],
       [ 189. ,    4.6,   93. ],
       [  95. ,    7.4,   87. ],
       [  92. ,   15.5,   84. ],
       [ 252. ,   10.9,   80. ],
       [ 220. ,   10.3,   78. ],
       [ 230. ,   10.9,   75. ],
       [ 259. ,    9.7,   73. ],
       [ 236. ,   14.9,   81. ],
       [ 259. ,   15.5,   76. ],
       [ 238. ,    6.3,   77. ],
       [  24. ,   10.9,   71. ],
       [ 112. ,   11.5,   71. ],
       [ 237. ,    6.9,   78. ],
       [ 224. ,   13.8,   67. ],
       [  27. ,   10.3,   76. ],
       [ 238. ,   10.3,   68. ],
       [ 201. ,    8. ,   82. ],
       [ 238. ,   12.6,   64. ],
       [  14. ,    9.2,   71. ],
       [ 139. ,   10.3,   81. ],
       [  49. ,   10.3,   69. ],
       [  20. ,   16.6,   63. ],
       [ 193. ,    6.9,   70. ],
       [ 145. ,   13.2,   77. ],
       [ 191. ,   14.3,   75. ],
       [ 131. ,    8. ,   76. ],
       [ 223. ,   11.5,   68. ]])

In [10]:
y

array([  41. ,   36. ,   12. ,   18. ,   31.5,   28. ,   23. ,   19. ,
          8. ,   31.5,    7. ,   16. ,   11. ,   14. ,   18. ,   14. ,
         34. ,    6. ,   30. ,   11. ,    1. ,   11. ,    4. ,   32. ,
         31.5,   31.5,   31.5,   23. ,   45. ,  115. ,   37. ,   31.5,
         31.5,   31.5,   31.5,   31.5,   31.5,   29. ,   31.5,   71. ,
         39. ,   31.5,   31.5,   23. ,   31.5,   31.5,   21. ,   37. ,
         20. ,   12. ,   13. ,   31.5,   31.5,   31.5,   31.5,   31.5,
         31.5,   31.5,   31.5,   31.5,   31.5,  135. ,   49. ,   32. ,
         31.5,   64. ,   40. ,   77. ,   97. ,   97. ,   85. ,   31.5,
         10. ,   27. ,   31.5,    7. ,   48. ,   35. ,   61. ,   79. ,
         63. ,   16. ,   31.5,   31.5,   80. ,  108. ,   20. ,   52. ,
         82. ,   50. ,   64. ,   59. ,   39. ,    9. ,   16. ,   78. ,
         35. ,   66. ,  122. ,   89. ,  110. ,   31.5,   31.5,   44. ,
         28. ,   65. ,   31.5,   22. ,   59. ,   23. ,   31. ,   44. ,
         21. ,    9. ,   31.5,   45. ,  168. ,   73. ,   31.5,   76. ,
        118. ,   84. ,   85. ,   96. ,   78. ,   73. ,   91. ,   47. ,
         32. ,   20. ,   23. ,   21. ,   24. ,   44. ,   21. ,   28. ,
          9. ,   13. ,   46. ,   18. ,   13. ,   24. ,   16. ,   13. ,
         23. ,   36. ,    7. ,   14. ,   30. ,   31.5,   14. ,   18. ,
         20. ])

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
x_train

array([[ 189. ,    4.6,   93. ],
       [ 137. ,   11.5,   86. ],
       [  83. ,    6.9,   81. ],
       [  25. ,    9.7,   61. ],
       [ 314. ,   10.9,   83. ],
       [ 205. ,    4.6,   87. ],
       [ 237. ,    6.9,   78. ],
       [  13. ,   12. ,   67. ],
       [ 145. ,   13.2,   77. ],
       [ 131. ,    8. ,   76. ],
       [ 322. ,   11.5,   79. ],
       [ 322. ,   11.5,   68. ],
       [  31. ,   14.9,   77. ],
       [ 279. ,    7.4,   76. ],
       [ 191. ,   14.3,   75. ],
       [ 175. ,   14.9,   81. ],
       [ 149. ,   12.6,   74. ],
       [ 259. ,   15.5,   76. ],
       [ 148. ,    8. ,   82. ],
       [ 205. ,    6.9,   74. ],
       [ 205. ,    7.4,   85. ],
       [ 237. ,    6.3,   96. ],
       [  20. ,   16.6,   63. ],
       [ 197. ,    5.1,   92. ],
       [ 269. ,    4.1,   84. ],
       [ 139. ,    8.6,   82. ],
       [ 223. ,    8. ,   85. ],
       [ 248. ,    9.2,   85. ],
       [ 285. ,    6.3,   84. ],
       [  92. ,   15.5,   84. ],
       [  14. ,    9.2,   71. ],
       [ 244. ,   10.9,   78. ],
       [  71. ,   10.3,   77. ],
       [ 137. ,   10.3,   76. ],
       [ 275. ,    7.4,   86. ],
       [ 101. ,   10.9,   84. ],
       [  24. ,   13.8,   81. ],
       [ 205. ,    6.9,   86. ],
       [ 120. ,   11.5,   73. ],
       [  37. ,    9.2,   65. ],
       [ 274. ,   10.9,   68. ],
       [ 259. ,    9.7,   73. ],
       [ 252. ,   10.9,   80. ],
       [   8. ,    9.7,   59. ],
       [ 334. ,   11.5,   64. ],
       [  59. ,    1.7,   76. ],
       [ 260. ,    6.9,   81. ],
       [ 313. ,   11.5,   62. ],
       [ 223. ,   11.5,   68. ],
       [ 253. ,    7.4,   83. ],
       [ 299. ,    8.6,   65. ],
       [ 267. ,    6.3,   92. ],
       [  36. ,   14.3,   72. ],
       [ 294. ,    8.6,   86. ],
       [ 207. ,    8. ,   90. ],
       [ 290. ,    9.2,   66. ],
       [  64. ,   11.5,   79. ],
       [ 183. ,    2.8,   93. ],
       [  51. ,    6.3,   79. ],
       [ 220. ,   10.3,   78. ],
       [ 191. ,   14.9,   77. ],
       [ 256. ,    9.7,   69. ],
       [ 255. ,   12.6,   75. ],
       [ 225. ,    2.3,   94. ],
       [ 259. ,   10.9,   93. ],
       [ 188. ,    6.3,   94. ],
       [ 118. ,    8. ,   72. ],
       [ 153. ,    5.7,   88. ],
       [ 238. ,   10.3,   68. ],
       [ 250. ,    9.2,   92. ],
       [ 205. ,   14.3,   56. ],
       [ 230. ,   10.9,   75. ],
       [  78. ,   18.4,   57. ],
       [ 273. ,    6.9,   87. ],
       [ 205. ,   14.9,   66. ],
       [  91. ,    4.6,   76. ],
       [  49. ,   10.3,   69. ],
       [ 115. ,    7.4,   76. ],
       [ 190. ,    7.4,   67. ],
       [ 186. ,    9.2,   84. ],
       [ 252. ,   14.9,   81. ],
       [ 135. ,    8. ,   75. ],
       [  48. ,   14.3,   80. ],
       [ 220. ,    8.6,   85. ],
       [  92. ,   12. ,   61. ],
       [ 238. ,    3.4,   81. ],
       [ 291. ,   14.9,   91. ],
       [ 286. ,    8.6,   78. ],
       [ 167. ,    6.9,   91. ],
       [  47. ,   10.3,   73. ],
       [ 236. ,   14.9,   81. ],
       [ 175. ,    4.6,   83. ],
       [ 287. ,    9.7,   74. ],
       [ 201. ,    8. ,   82. ],
       [  65. ,   13.2,   58. ],
       [  95. ,    7.4,   87. ],
       [  44. ,    9.7,   62. ],
       [ 223. ,    5.7,   79. ],
       [ 229. ,   10.3,   90. ],
       [ 258. ,    9.7,   81. ],
       [ 187. ,    5.1,   87. ],
       [ 212. ,    9.7,   79. ],
       [ 193. ,    6.9,   70. ],
       [ 264. ,   14.3,   73. ],
       [ 274. ,   10.3,   82. ],
       [ 266. ,   14.9,   58. ],
       [   7. ,    6.9,   74. ],
       [ 238. ,   12.6,   64. ],
       [ 139. ,   10.3,   81. ],
       [ 291. ,   13.8,   90. ],
       [  98. ,   11.5,   80. ],
       [  27. ,   10.3,   76. ],
       [ 213. ,    7.4,   88. ],
       [ 175. ,    7.4,   89. ],
       [  82. ,   12. ,   86. ],
       [ 264. ,   14.3,   79. ],
       [ 320. ,   16.6,   73. ],
       [ 194. ,    8.6,   69. ],
       [ 192. ,   11.5,   86. ],
       [ 276. ,    5.1,   88. ],
       [ 215. ,    8. ,   86. ],
       [ 284. ,   20.7,   72. ]])

In [13]:
y_train

array([  91. ,   31.5,   39. ,    4. ,   40. ,   66. ,   46. ,   23. ,
         31.5,   18. ,   31.5,   30. ,   31.5,   37. ,   14. ,   27. ,
         12. ,   21. ,   23. ,    7. ,   35. ,   84. ,   14. ,   78. ,
        135. ,   31.5,  108. ,   49. ,   61. ,   32. ,   23. ,   31. ,
         22. ,   13. ,   50. ,   31.5,    9. ,   78. ,   12. ,   20. ,
         14. ,   24. ,   20. ,    1. ,   14. ,   31.5,   48. ,   18. ,
         20. ,   64. ,   23. ,   97. ,    9. ,   80. ,  110. ,   11. ,
         31.5,   73. ,   59. ,   23. ,   21. ,   16. ,   31.5,  118. ,
         31.5,   85. ,   36. ,   31.5,   24. ,   31.5,   31.5,   21. ,
          6. ,   31.5,   28. ,   31.5,    7. ,   23. ,   41. ,   31.5,
         45. ,   31.5,    7. ,   31.5,   32. ,  168. ,   31.5,   31.5,
         96. ,   31.5,   44. ,   64. ,   31.5,   16. ,   18. ,   47. ,
         11. ,  115. ,   89. ,   31.5,   79. ,   45. ,   30. ,   10. ,
         35. ,   31.5,   16. ,   13. ,   36. ,   71. ,   31.5,   13. ,
         82. ,   85. ,   52. ,   31.5,   11. ,   31.5,   44. ,   77. ,
         73. ,   37. ])

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
mlr=LinearRegression()

In [16]:
mlr.fit(x_train,y_train)#to train a machine fit is used

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
y_pred=mlr.predict(x_test)#returns predicited values

In [18]:
y_pred

array([ 18.05225247,  52.51701913,  49.00746162,  41.59792626,
       -16.1929563 ,  -3.0051768 ,  39.04837707,  65.10248641,
        25.57254675,  51.83323424,  43.36123014,  46.8037294 ,
        46.70953083,  15.08446258,  45.45330493,  55.15335893,
         9.07638449,  38.90881508,  76.82889654,  67.49756386,
        42.34734018, -24.10751878,  18.01157447,  46.53393961,
        42.62288899,  76.95162673,  21.20102609,  49.82044826,
        50.03528281,  47.49211553,  23.96121723])

In [19]:
y_test

array([  31.5,   28. ,   32. ,   65. ,   31.5,   19. ,   31.5,   31.5,
         21. ,   31.5,   20. ,   16. ,   31.5,   18. ,   28. ,   39. ,
         31.5,   44. ,   97. ,   76. ,   31.5,    8. ,    9. ,   63. ,
         29. ,  122. ,   13. ,   31.5,   59. ,   31.5,   34. ])

In [20]:
mlr.intercept_

-47.213740220240858

In [21]:
mlr.coef_ #state has two values 0 0,1 0,0 1 like that so we have 5 columns

array([ 0.05710118, -3.05908664,  1.36899903])

In [22]:
from sklearn.metrics import r2_score #to find performance of  our model

In [23]:
r2_score(y_test,y_pred)

0.26171305788733334

In [24]:
!pip install watson-machine-learning-client --upgrade

Requirement already up-to-date: watson-machine-learning-client in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (1.0.365)
Requirement not upgraded as not directly required: pandas in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (0.21.0)
Requirement not upgraded as not directly required: lomond in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (0.1.13)
Requirement not upgraded as not directly required: tabulate in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (0.8.2)
Requirement not upgraded as not directly required: tqdm in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (4.19.5)
Requirement not upgraded as not directly required: requests in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (2.18.4)
Requirement not upgraded as not directly required: urllib3 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (1.22)
Requirement not upgraded as not directly required: ibm-cos-sdk in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (2.0.1)
Requirement not upgraded as not directly required: certifi in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from watson-machine-learning-client) (2019.3.9)
Requirement not upgraded as not directly required: python-dateutil>=2 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from pandas->watson-machine-learning-client) (2.6.1)
Requirement not upgraded as not directly required: pytz>=2011k in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from pandas->watson-machine-learning-client) (2018.3)
Requirement not upgraded as not directly required: numpy>=1.9.0 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from pandas->watson-machine-learning-client) (1.13.3)
Requirement not upgraded as not directly required: six>=1.10.0 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from lomond->watson-machine-learning-client) (1.11.0)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from requests->watson-machine-learning-client) (3.0.4)
Requirement not upgraded as not directly required: idna<2.7,>=2.5 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from requests->watson-machine-learning-client) (2.6)
Requirement not upgraded as not directly required: ibm-cos-sdk-s3transfer==2.*,>=2.0.0 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from ibm-cos-sdk->watson-machine-learning-client) (2.0.1)
Requirement not upgraded as not directly required: ibm-cos-sdk-core==2.*,>=2.0.0 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from ibm-cos-sdk->watson-machine-learning-client) (2.0.1)
Requirement not upgraded as not directly required: jmespath<1.0.0,>=0.7.1 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from ibm-cos-sdk-core==2.*,>=2.0.0->ibm-cos-sdk->watson-machine-learning-client) (0.9.3)
Requirement not upgraded as not directly required: docutils>=0.10 in /opt/conda/envs/DSX-Python35/lib/python3.5/site-packages (from ibm-cos-sdk-core==2.*,>=2.0.0->ibm-cos-sdk->watson-machine-learning-client) (0.14)
tensorflow 1.3.0 requires tensorflow-tensorboard<0.2.0,>=0.1.0, which is not installed.

In [25]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
2019-05-24 08:55:10,980 - watson_machine_learning_client.metanames - WARNING - 'AUTHOR_EMAIL' meta prop is deprecated. It will be ignored.

In [26]:
wml_credentials = {
  "username": "9fa0d778-611b-4351-bf90-e2350d020067",
  "password": "e40adc3d-29d2-4962-aee0-d6a2ec92b62a",
  "instance_id": "b773a13e-5dbe-4432-b29b-68374ec6681b",
  "url":"https://eu-gb.ml.cloud.ibm.com"
}

In [27]:
client = WatsonMachineLearningAPIClient(wml_credentials)

In [28]:
model_props = {client.repository.ModelMetaNames.AUTHOR_NAME: "Vamsi", 
               client.repository.ModelMetaNames.AUTHOR_EMAIL: "balavamsilanke1@gmail.com", 
               client.repository.ModelMetaNames.NAME: "air quality"
              }

In [29]:
model =client.repository.store_model(mlr, meta_props=model_props)

In [30]:
client.repository.list_models()

------------------------------------  -----------  ------------------------  -----------------
GUID                                  NAME         CREATED                   FRAMEWORK
516d76ff-6e53-4375-b095-84cdcb22ba1a  air quality  2019-05-24T08:55:11.176Z  scikit-learn-0.19
e7a0750a-ee37-4263-9003-7f0c28c8995b  MLR MODEL    2019-05-15T04:19:14.496Z  scikit-learn-0.19
0538a271-c39a-4d14-a32a-580d21bdb33b  MLR MODEL    2019-05-14T07:34:38.980Z  scikit-learn-0.19
------------------------------------  -----------  ------------------------  -----------------

In [31]:
published_model_uid = client.repository.get_model_uid(model)
published_model_uid

'516d76ff-6e53-4375-b095-84cdcb22ba1a'

In [32]:
deployment = client.deployments.create(published_model_uid, name="air quality")

#######################################################################################

Synchronous deployment creation for uid: '516d76ff-6e53-4375-b095-84cdcb22ba1a' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='68618aec-4e3a-4f09-a8de-b36f5da7608a'
------------------------------------------------------------------------------------------------

In [33]:
scoring_endpoint = client.deployments.get_scoring_url(deployment)
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/b773a13e-5dbe-4432-b29b-68374ec6681b/deployments/68618aec-4e3a-4f09-a8de-b36f5da7608a/online'